version: "3.8"

services:
    pgsql: # docker-compose run pgsql bash
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: pet_db
        #volumes:
            #- .docker/pgsql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
            - 5438:5432
